# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/PCID/processador_DCP/processador_DCP.cache/wt [current_project]
set_property parent.project_path D:/PCID/processador_DCP/processador_DCP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet D:/PCID/processador_DCP/processador_DCP.srcs/sources_1/imports/processador_top/processador_top.dcp
set_property used_in_implementation false [get_files D:/PCID/processador_DCP/processador_DCP.srcs/sources_1/imports/processador_top/processador_top.dcp]
read_verilog -library xil_defaultlib -sv {
  D:/PCID/processador_DCP/processador_DCP.srcs/sources_1/new/memoria_instrucoes.sv
  D:/PCID/processador_DCP/processador_DCP.srcs/sources_1/new/top_module.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/PCID/processador_DCP/processador_DCP.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/PCID/processador_DCP/processador_DCP.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]


synth_design -top top_module -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
