# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Haroldo/Documents/PCID/processador/processador.cache/wt [current_project]
set_property parent.project_path C:/Users/Haroldo/Documents/PCID/processador/processador.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/register.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/zero.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/PC_somador.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/PC.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/mux4.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/memoria.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/IR.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/bloco_controle.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/banco_registradores.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/ALU.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/unidade_controle.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/decoder_7seg.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/bloco_operacional.sv
  C:/Users/Haroldo/Documents/PCID/processador/processador.srcs/sources_1/new/processador_top.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top processador_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef processador_top.dcp

catch { report_utilization -file processador_top_utilization_synth.rpt -pb processador_top_utilization_synth.pb }
